# Generated by Django 3.2.8 on 2021-11-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_code', models.CharField(max_length=200, null=True)),
                ('operator', models.CharField(choices=[('Malawi Government', 'Malawi Government'), ('CHAM', 'CHAM'), ('Private', 'Private')], max_length=200, null=True)),
                ('facility_type', models.CharField(choices=[('Health Centre', 'Health Centre'), ('District Hospital', 'District Hospital'), ('Clinic', 'Clinic'), ('Rural Community Hospital', 'Rural Community Hospital')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample_Volumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], max_length=200, null=True)),
            ],
        ),
    ]
