# Generated by Django 3.2.8 on 2021-11-14 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sample_volumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='edited_at',
        ),
        migrations.AddField(
            model_name='facility',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample_volumes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample_volumes',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_volumes.facility'),
        ),
        migrations.AddField(
            model_name='sample_volumes',
            name='sample_type',
            field=models.CharField(choices=[('VL', 'VL'), ('EID', 'EID'), ('TB', 'TB'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
