# Generated by Django 3.2.8 on 2021-11-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0002_auto_20211114_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_volumes',
            name='volume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
