# Generated by Django 3.2.8 on 2021-11-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0003_sample_volumes_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_volumes',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
