# Generated by Django 3.2.8 on 2021-11-26 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0006_courier_district_health_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_volumes.district'),
        ),
    ]
