# Generated by Django 3.2.8 on 2021-11-27 15:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0008_auto_20211127_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='health_worker',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
