# Generated by Django 3.2.8 on 2021-11-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0009_auto_20211127_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='commcare_id',
            new_name='commcare_user_id',
        ),
        migrations.RenameField(
            model_name='health_worker',
            old_name='postition',
            new_name='position',
        ),
    ]
