# Generated by Django 3.2.8 on 2021-12-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0011_auto_20211208_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_code',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sampletype',
            name='sample_code',
            field=models.IntegerField(unique=True),
        ),
    ]
