# Generated by Django 3.2.8 on 2021-12-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0012_auto_20211208_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_volumes',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
