# Generated by Django 3.2.8 on 2021-12-08 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_volumes', '0013_alter_sample_volumes_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_volumes',
            name='reported_date',
            field=models.DateTimeField(default=datetime.date(2021, 12, 8), null=True),
        ),
    ]
